#! /bin/sh

# Use this file instead of ./classpath to use code built by Maven ('mvn install').
# Don't forget to adjust version numbers if necessary.

# This might need '-SNAPSHOT' added to it if you're using the up-to-date code from source control repository
# (NOTE: There is no '3.6.7' at this point, just the snapshot)
DZ_VERSION=3.6.8-SNAPSHOT

JUKEBOX_VERSION=7.0.0-SNAPSHOT
SERVOMASTER_VERSION=2.0.0-SNAPSHOT
GOOGLE_OAUTH_VERSION=1.19.0
GOOGLE_CALENDAR_VERSION=v3-rev104-1.19.0
JETTY_VERSION=6.1.26
LOG4J_VERSION=2.11.0
XBEE_API_VERSION=0.9.1-dz

LIBDIR=${HOME}/.m2/repository

COMMONS_CODEC=${LIBDIR}/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
COMMONS_LANG=${LIBDIR}/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
COMMONS_LOGGING=${LIBDIR}/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
LOG4J_API=${LIBDIR}/org/apache/logging/log4j/log4j-api/${LOG4J_VERSION}/log4j-api-${LOG4J_VERSION}.jar
LOG4J_CORE=${LIBDIR}/org/apache/logging/log4j/log4j-core/${LOG4J_VERSION}/log4j-core-${LOG4J_VERSION}.jar
HTTPCORE=${LIBDIR}/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
HTTPCLIENT=${LIBDIR}/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar
JODA_TIME=${LIBDIR}/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar
SPRING=${LIBDIR}/org/springframework/spring/2.5.6/spring-2.5.6.jar
GSON=${LIBDIR}/com/google/code/gson/gson/1.7.1/gson-1.7.1.jar
XBEE_API=${LIBDIR}/com/rapplogic/xbeeapi/${XBEE_API_VERSION}/xbeeapi-${XBEE_API_VERSION}.jar

DZ=${LIBDIR}/net/sf/dz3
JUKEBOX=${LIBDIR}/net/sf/jukebox
SERVOMASTER=${LIBDIR}/net/sf/servomaster

export CLASSPATH="./conf:\
${DZ}/dz3-model/${DZ_VERSION}/dz3-model-${DZ_VERSION}.jar:\
${DZ}/dz3-common/${DZ_VERSION}/dz3-common-${DZ_VERSION}.jar:\
${DZ}/dz3-connector/${DZ_VERSION}/dz3-connector-${DZ_VERSION}.jar:\
${DZ}/dz3-http/${DZ_VERSION}/dz3-http-${DZ_VERSION}.jar:\
${DZ}/dz3-sensors/${DZ_VERSION}/dz3-sensors-${DZ_VERSION}.jar:\
${DZ}/dz3-scheduler/${DZ_VERSION}/dz3-scheduler-${DZ_VERSION}.jar:\
${DZ}/dz3-scheduler-gcal-v3/${DZ_VERSION}/dz3-scheduler-gcal-v3-${DZ_VERSION}.jar:\
${DZ}/dz3-spring/${DZ_VERSION}/dz3-spring-${DZ_VERSION}.jar:\
${DZ}/dz3-owapi/${DZ_VERSION}/dz3-owapi-${DZ_VERSION}.jar:\
${DZ}/dz3-servomaster/${DZ_VERSION}/dz3-servomaster-${DZ_VERSION}.jar:\
${DZ}/dz3-swing/${DZ_VERSION}/dz3-swing-${DZ_VERSION}.jar:\
${DZ}/dz3-xbee/${DZ_VERSION}/dz3-xbee-${DZ_VERSION}.jar:\
/usr/share/java/RXTXcomm.jar:\
/usr/share/java/jsr80.jar:\
/usr/share/java/jsr80_linux.jar:\
/usr/share/java/jsr80_ri.jar:\
${JUKEBOX}/jukebox-common/${JUKEBOX_VERSION}/jukebox-common-${JUKEBOX_VERSION}.jar:\
${JUKEBOX}/jukebox-datastream/${JUKEBOX_VERSION}/jukebox-datastream-${JUKEBOX_VERSION}.jar:\
${JUKEBOX}/jukebox-jmx/${JUKEBOX_VERSION}/jukebox-jmx-${JUKEBOX_VERSION}.jar:\
${JUKEBOX}/jukebox-sem/${JUKEBOX_VERSION}/jukebox-sem-${JUKEBOX_VERSION}.jar:\
${JUKEBOX}/jukebox-service/${JUKEBOX_VERSION}/jukebox-service-${JUKEBOX_VERSION}.jar:\
${SERVOMASTER}/servomaster-common/${SERVOMASTER_VERSION}/servomaster-common-${SERVOMASTER_VERSION}.jar:\
${SERVOMASTER}/servomaster-raspberry-pi/${SERVOMASTER_VERSION}/servomaster-raspberry-pi-${SERVOMASTER_VERSION}.jar:\
${SERVOMASTER}/servomaster-serial/${SERVOMASTER_VERSION}/servomaster-serial-${SERVOMASTER_VERSION}.jar:\
${SERVOMASTER}/servomaster-usb/${SERVOMASTER_VERSION}/servomaster-usb-${SERVOMASTER_VERSION}.jar:\
${COMMONS_CODEC}:\
${COMMONS_LANG}:\
${COMMONS_LOGGING}:\
${HTTPCORE}:\
${HTTPCLIENT}:\
${JODA_TIME}:\
${LOG4J_API}:\
${LOG4J_CORE}:\
${SPRING}:\
${GSON}:\
${XBEE_API}:\
${LIBDIR}/com/google/api-client/google-api-client/${GOOGLE_OAUTH_VERSION}/google-api-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/http-client/google-http-client/${GOOGLE_OAUTH_VERSION}/google-http-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/http-client/google-http-client-jackson2/${GOOGLE_OAUTH_VERSION}/google-http-client-jackson2-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/oauth-client/google-oauth-client/${GOOGLE_OAUTH_VERSION}/google-oauth-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/oauth-client/google-oauth-client-java6/${GOOGLE_OAUTH_VERSION}/google-oauth-client-java6-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/oauth-client/google-oauth-client-jetty/${GOOGLE_OAUTH_VERSION}/google-oauth-client-jetty-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/com/google/apis/google-api-services-calendar/${GOOGLE_CALENDAR_VERSION}/google-api-services-calendar-${GOOGLE_CALENDAR_VERSION}.jar:\
${LIBDIR}/com/fasterxml/jackson/core/jackson-core/2.1.3/jackson-core-2.1.3.jar:\
${LIBDIR}/org/mortbay/jetty/jetty/${JETTY_VERSION}/jetty-${JETTY_VERSION}.jar:\
${LIBDIR}/org/mortbay/jetty/jetty-util/${JETTY_VERSION}/jetty-util-${JETTY_VERSION}.jar:\
${LIBDIR}/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar"

echo $CLASSPATH | tr ":" "\n"
