#! /bin/sh

if test -z "${BASENAME}"; then
    echo "This script must only be run from dz-runner";
    exit 1;
fi

LIBDIR=${BASENAME}/lib

DZ_VERSION=3.6.8-SNAPSHOT
JUKEBOX_VERSION=7.0.0-SNAPSHOT
SERVOMASTER_VERSION=2.0.0-SNAPSHOT
GOOGLE_OAUTH_VERSION=1.19.0
GOOGLE_CALENDAR_VERSION=v3-rev104-1.19.0
JETTY_VERSION=6.1.26
LOG4J_VERSION=2.11.0
XBEE_API_VERSION=0.9.1-dz

export CLASSPATH="./conf:\
${LIBDIR}/dz3-model-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-common-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-connector-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-http-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-sensors-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-spring-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-owapi-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-owfs-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-scheduler-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-scheduler-gcal-v3-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-servomaster-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-swing-${DZ_VERSION}.jar:\
${LIBDIR}/dz3-xbee-${DZ_VERSION}.jar:\
${LIBDIR}/jukebox-common-${JUKEBOX_VERSION}.jar:\
${LIBDIR}/jukebox-datastream-${JUKEBOX_VERSION}.jar:\
${LIBDIR}/jukebox-jmx-${JUKEBOX_VERSION}.jar:\
${LIBDIR}/jukebox-sem-${JUKEBOX_VERSION}.jar:\
${LIBDIR}/jukebox-service-${JUKEBOX_VERSION}.jar:\
${LIBDIR}/servomaster-common-${SERVOMASTER_VERSION}.jar:\
${LIBDIR}/servomaster-raspberry-pi-${SERVOMASTER_VERSION}.jar:\
${LIBDIR}/servomaster-serial-${SERVOMASTER_VERSION}.jar:\
${LIBDIR}/servomaster-usb-${SERVOMASTER_VERSION}.jar:\
${LIBDIR}/commons-codec-1.10.jar:\
${LIBDIR}/commons-lang3-3.3.2.jar:\
${LIBDIR}/commons-logging-1.1.1.jar:\
${LIBDIR}/httpcore-4.4.10.jar:\
${LIBDIR}/httpclient-4.5.6.jar:\
${LIBDIR}/joda-time-2.8.1.jar:\
${LIBDIR}/log4j-api-${LOG4J_VERSION}.jar:\
${LIBDIR}/log4j-core-${LOG4J_VERSION}.jar:\
${LIBDIR}/spring-2.5.6.jar:\
${LIBDIR}/google-api-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-http-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-http-client-jackson2-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-oauth-client-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-oauth-client-java6-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-oauth-client-jetty-${GOOGLE_OAUTH_VERSION}.jar:\
${LIBDIR}/google-api-services-calendar-${GOOGLE_CALENDAR_VERSION}.jar:\
${LIBDIR}/jackson-core-2.1.3.jar:\
${LIBDIR}/jetty-${JETTY_VERSION}.jar:\
${LIBDIR}/jetty-util-${JETTY_VERSION}.jar:\
${LIBDIR}/servlet-api-2.5-6.1.5.jar:\
${LIBDIR}/gson-1.7.1.jar:\
${LIBDIR}/xbeeapi-${XBEE_API_VERSION}.jar:\
/usr/share/java/RXTXcomm.jar"

echo $CLASSPATH | tr ":" "\n"
