#! /bin/sh

# The following line will raise the priority of the running DZ instance to the maximum.

if [ "root" != "$USER" ]; then
	echo "You have to be root to run this (or use sudo)";
	exit 1;
fi

renice -20 `ps ax|grep net.sf.dz3.runtime.Container|grep -v grep|tr -s " "|sed -e "s:^ ::;"|cut -f 1 -d " "`
