
# /actuator/metrics endpoint

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

  influx:
    metrics:
      export:
        enabled: true
        db: hcc-micrometer
        step: 10s
        uri: http://localhost:8086
  jmx:
    metrics:
      export:
        enabled: true
        domain: net.sf.dz3.springboot


logging:
  level:
    io.micrometer: INFO
